#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - jq
  - golang
  - docker.io
  - docker-compose
  - lxc
  - lxctl
  - lxc-templates

runcmd:
  - [hostnamectl, set-hostname, cloud-lab]
  - [systemctl, enable, docker]
  - [systemctl, start, docker]
  - [usermod, -aG, docker, ubuntu]

final_message: "System setup completed!"